services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: LGCUser
      POSTGRES_PASSWORD: LGCPassword
      POSTGRES_DB: LGC_DB
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - LGCNetwork

volumes:
  postgres_data:
    driver: local

networks:
  LGCNetwork:
    name: LGCNetwork
    driver: bridge
    external: true
